runtime: go113

handlers:
- url: /
  static_files: static/htm/index.htm
  upload: static/htm/index.htm

- url: /view.htm
  static_files: static/htm/view.htm
  upload: static/htm/view.htm

- url: /db/insert_word
  script: _go_app

- url: /db/select_word
  script: _go_app

- url: /db/insert_video
  script: _go_app

- url: /db/select_video
  script: _go_app

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css
